const actionLabels: Record<string, string> = {
  'activity_request.approve': '탐구활동서 승인',
  'activity_request.delete': '탐구활동서 삭제',
  'activity_request.issue': '탐구활동서 발급',
  'activity_request.print_batch': '탐구활동서 일괄 인쇄',
  'activity_request.reject': '탐구활동서 반려',
  'admin.account-activation.bulk-issue': '계정 인증코드 일괄 발급',
  'admin.account-activation.issue': '계정 인증코드 발급',
  'admin.account.deactivate': '계정 비활성화',
  'admin.role.create': '역할 생성',
  'admin.role.permissions.assign': '역할 권한 변경',
  'admin.role.update': '역할 수정',
  'admin.staff.create': '교직원 계정 생성',
  'admin.staff.update': '교직원 정보 수정',
  'admin.student-roster.apply': '학생 명단 반영',
  'admin.student.create': '학생 계정 생성',
  'admin.student.update': '학생 정보 수정',
  'admin.user.roles.assign': '사용자 역할 변경',
  'auth.account-activation.complete': '계정 활성화 완료',
  'auth.login': '로그인',
  'auth.password_reset.confirm': '비밀번호 재설정 완료',
  'auth.password_reset.request': '비밀번호 재설정 요청',
  'auth.sso.exchange': '통합로그인 연결',
  'board.comment.create': '댓글 작성',
  'board.comment.hide': '댓글 숨김',
  'board.comment.show': '댓글 공개',
  'board.poll.vote': '게시글 투표 참여',
  'board.post.create': '게시글 작성',
  'board.post.delete': '게시글 삭제',
  'board.post.draft.delete': '임시저장 글 삭제',
  'board.post.hide': '게시글 숨김',
  'board.post.pin': '게시글 고정',
  'board.post.publish': '게시글 등록',
  'board.post.show': '게시글 공개',
  'board.post.unpin': '게시글 고정 해제',
  'board.post.update': '게시글 수정',
  cancel: '상벌점 기록 취소',
  'content.report.create': '콘텐츠 신고',
  'content.report.status': '신고 처리 상태 변경',
  'device_case.bulk-close': '보관함 전체 잠금',
  'device_case.bulk-open': '보관함 전체 잠금 해제',
  'device_case.close': '보관함 잠금',
  'device_case.open': '보관함 잠금 해제',
  'dorm.assignment.cancel': '기숙사 배정 취소',
  'dorm.assignment.create': '기숙사 배정',
  'dorm.assignment.move': '기숙사 방 이동',
  'dorm.assignment.swap': '기숙사 방 교환',
  'dorm.draw.apply': '기숙사 추첨 반영',
  'dorm.report.create': '기숙사 민원 등록',
  'dorm.report.status.update': '기숙사 민원 상태 변경',
  'dorm.roommate-block.create': '기숙사 블랙리스트 등록',
  'dorm.roommate-block.delete': '기숙사 블랙리스트 삭제',
  'file.upload': '파일 업로드',
  graduate: '졸업 처리',
  'jbs.post.create': 'JBS 게시글 작성',
  'jbs.post.delete': 'JBS 게시글 삭제',
  'jbs.post.update': 'JBS 게시글 수정',
  'lost-item.create': '분실물 등록',
  'lost-item.delete': '분실물 삭제',
  'lost-item.status': '분실물 상태 변경',
  'lost-item.update': '분실물 수정',
  'me.contact.email.update': '이메일 수정',
  'me.contact.phone.update': '연락처 수정',
  'me.profile.update': '내 정보 수정',
  'me.profile_image.delete': '프로필 이미지 삭제',
  'notice.create': '공지 작성',
  'notice.delete': '공지 삭제',
  'notice.update': '공지 수정',
  'petition.answer': '청원 답변',
  'petition.create': '청원 작성',
  'petition.delete': '청원 삭제',
  'petition.participate': '청원 참여',
  'petition.update': '청원 수정',
  'points.departure-case.complete': '퇴사 상벌점 반감 완료',
  'points.departure-case.dismiss': '퇴사 상벌점 반감 제외',
  'points.departure-case.requested': '퇴사 상벌점 반감 요청',
  'points.departure-cases.sync': '퇴사 대상 동기화',
  'points.reason.create': '상벌점 사유 생성',
  'points.reason.update': '상벌점 사유 수정',
  'points.record.batch-create': '상벌점 일괄 부여',
  'points.record.cancel': '상벌점 기록 취소',
  'points.record.create': '상벌점 부여',
  'points.record.restore': '상벌점 기록 복구',
  'points.semester-half.apply': '학기 상벌점 반감 적용',
  'points.semester-half.requested': '학기 상벌점 반감 요청',
  restore: '상벌점 기록 복구',
  'school-event.create': '학사일정 등록',
  'school-event.delete': '학사일정 삭제',
  'school-event.import': '학사일정 가져오기',
  'school-event.import.replace': '학사일정 교체 가져오기',
  'school-event.update': '학사일정 수정',
  'wake_song.request.approved': '기상곡 승인',
  'wake_song.request.canceled': '기상곡 취소',
  'wake_song.request.create': '기상곡 신청',
  'wake_song.request.played': '기상곡 재생 완료',
  'wake_song.request.rejected': '기상곡 반려',
  'wake_song.request.scheduled': '기상곡 편성',
  'wake_song.request.update': '기상곡 신청 수정',
};

const targetLabels: Record<string, string> = {
  activity_requests: '탐구활동서',
  comments: '댓글',
  device_cases: '휴대폰 보관함',
  dorm_assignments: '기숙사 배정',
  dorm_reports: '기숙사 민원',
  dorm_roommate_blocks: '기숙사 블랙리스트',
  lost_items: '분실물',
  notice: '공지',
  notices: '공지',
  petitions: '청원',
  point_award_cases: '상벌점 반감 건',
  point_batches: '상벌점 일괄 작업',
  point_reasons: '상벌점 사유',
  point_records: '상벌점 기록',
  point_semester_halves: '학기 상벌점 반감',
  post: '게시글',
  posts: '게시글',
  profile: '프로필',
  reports: '신고',
  roles: '역할',
  roster_import_batches: '학생 명단 반영',
  school_events: '학사일정',
  staff_profiles: '교직원',
  student: '학생',
  students: '학생',
  users: '사용자',
  wake_song_requests: '기상곡 신청',
};

export function describeAuditAction(action: string) {
  return actionLabels[action] ?? '관리 작업';
}

export function describeAuditTarget(targetType?: string | null, targetId?: string | null) {
  if (!targetType) return '대상 없음';
  const label = targetLabels[targetType] ?? '기타 대상';
  return targetId ? `${label} #${targetId}` : label;
}
