services:
  api:
    environment:
      NODE_ENV: production
      ALLOW_DEV_AUTH: 'false'
    restart: unless-stopped

  web:
    restart: unless-stopped

  admin:
    restart: unless-stopped

  mysql:
    restart: unless-stopped

  redis:
    restart: unless-stopped
